import request from './request'
export const getInReport = params => request.get('/reports/in', { params })
export const getOutReport = params => request.get('/reports/out', { params })
export const getInventorySummary = params => request.get('/reports/inventory', { params })
export const getDashboardStats = (params) => request.get('/reports/dashboard', { params })
export const getLedgerReport = params => request.get('/reports/ledger', { params })
export const getStockMovementReport = params => request.get('/reports/stock-movement', { params })
export const getSupplierStatement = params => request.get('/reports/supplier-statement', { params })
export const getCustomerStatement = params => request.get('/reports/customer-statement', { params })
export const getStocktakeReport = params => request.get('/reports/stocktake', { params })
export const getGrossProfitReport = params => request.get('/reports/gross-profit', { params })
export const getProductProfitReport = params => request.get('/reports/product-profit', { params })
